#!/bin/bash

declare -a prog=("init" "login" "sh" "lower2upper" "grep" "more" "cat" "cp")

fail() {
    echo "Build Failed"
    exit 1
}

for i in "${prog[@]}"
do
    ./mku "$i"
    if [ $? -ne 0 ]; then fail; fi
done
